apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  template:
    metadata:
      name: app
      labels:
        app: app
    spec:
      containers:
        - name: mosaad-container
          image: gcr.io/ahmed-mossad/app
          ports:
            - containerPort: 8000
        - name: redis-container
          image: redis
          ports:
            - containerPort: 6379
  selector:
    matchLabels:
      app: app